[package]
name = "my-git-utils"
version = "0.2.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
git2 = "0.20.0"
inquire = "0.7.5"
log = "0.4.25"
seahorse = "2.2.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.138"
